---
title: "Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(p8105.datasets)
library(plotly)
library(patchwork)
```


Column {data-width=650}
-----------------------------------------------------------------------

### Chart A
```{r}
data("rest_inspec") 

rest_inspec = rest_inspec %>% 
  mutate(
    year = lubridate::year(inspection_date),
    month = as.factor(lubridate::month(inspection_date)),
    month = fct_recode(month, "Jan" = "1", "Feb" = "2", "Mar" = "3", "Apr" = "4", "May" = "5", "Jun" = "6", "Jul" = "7", "Aug" = "8", "Sep" = "9", "Oct" = "10", "Nov" = "11", "Dec" = "12")) %>% 
    filter(
      year == 2016,
      boro == "BRONX" | boro == "BROOKLYN" | boro == "MANHATTAN" | boro == "QUEENS" | boro == "STATEN ISLAND") 

violations_overtime = rest_inspec %>% 
  filter(
    inspection_type == "Cycle Inspection / Initial Inspection" | inspection_type == "Administrative Miscellaneous / Initial Inspection",
    critical_flag == "Critical" | critical_flag == "Not Critical") %>% 
  group_by(boro, month) %>% 
  summarize(count = n()) %>% 
  ungroup() %>% 
  ggplot(aes(x = month, y = count, color = boro, group = boro)) + 
  geom_line() +
  labs(
    x = "Month",
    y = "Number of all violations",
    title = "Number of violations for initial restaurant inspections in NYC by month, 2016"
  )

ggplotly(violations_overtime)
  
```

### Chart B
```{r}
mean_score = rest_inspec %>% 
  filter(
    inspection_type == "Cycle Inspection / Initial Inspection" | inspection_type == "Administrative Miscellaneous / Initial Inspection") %>% 
  ggplot(aes(x = boro, y = score)) +
    geom_boxplot() +
    labs(
      x = "Borough",
      y = "score",
      title = "Distribution of scores for intial inspections by borough, 2016"
    )

ggplotly(mean_score)
```


Column {data-width=350}
-----------------------------------------------------------------------

### Chart C1
```{r}
critical_violations = rest_inspec %>% 
  select(boro, cuisine_description, critical_flag) %>% 
  filter(boro == "MANHATTAN") %>% 
  group_by(cuisine_description) %>% 
  summarize(critical_pct = sum(
    critical_flag == "Critical")/sum(critical_flag == "Critical" | critical_flag == "Not Critical")) %>%
  ungroup() %>% 
  mutate(
    critical_rank = rank(-critical_pct),
    cuisine_description = as.factor(cuisine_description),
    cuisine_description = fct_reorder(cuisine_description, -critical_rank))

highest10 = critical_violations %>% 
  filter(critical_rank <= 10) %>% 
  ggplot(aes(x = cuisine_description, y = critical_pct)) +
  geom_bar(stat = "identity", fill = "red") +
  coord_flip() +
  labs(
    x = "",
    y = "Percent of violations deemed critical",
    title = "10 cuisines with highest percent critical violations") +
  scale_y_continuous(breaks = seq(from = 0, to = 1, by = 0.2), limits = c(0, 1))

ggplotly(highest10)
```


### Chart C2
```{r}
lowest10 = critical_violations %>% 
  filter(critical_rank >= 73) %>% 
  ggplot(aes(x = cuisine_description, y = critical_pct)) +
  geom_bar(stat = "identity", fill = "blue") +
  coord_flip() +
  labs(
    x = "Cuisine Type",
    y = "Percent of violations deemed critical",
    title = "10 cuisines with lowest percent critical violations") +
  scale_y_continuous(breaks = seq(from = 0, to = 1, by = 0.2), limits = c(0, 1))

ggplotly(lowest10)
```










